#!/bin/bash

PRT="asdasdasdadasdasasda"
PRT2="afdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfasafdfadfasfasfasfasfafasfasfadsfas"
MAX=5

WRSUM=0
WRMEAN=0

DWR=0
DWRMEAN=0

WVAR=0

for i in $(seq "$MAX") 
do
    # CM=$(printf "$CMON" $(seq $MAX))
    # printf "$CM\n"

    # printf `echo -e ''$_{1..10}'\b+'`
    # printf '%*s\n' "12" | tr ' ' "$CMON"
    # printf "%${i}s\n" "" | tr '' "$CMON"

    # PRT=`echo -e ''$_{1..$MAX}"\b$CMON"`
    # echo "$i"
    eval var$i=`./wrtest "$PRT"`
done

for i in $(seq "$MAX")
do
    temp="var$i"
    # echo ${!temp}
    let WRSUM=WRSUM+temp
    let DWR=DWR+\(temp\*temp\)
done

let WRMEAN=WRSUM/MAX
let DWRMEAN=DWR/MAX
let WVAR=DWRMEAN-\(WRMEAN\*WRMEAN\)

echo short-input write mean=$WRMEAN
echo short-input write var=$WVAR

# phase 2 (long long string input)

WRSUM=0
WRMEAN=0

DWR=0
DWRMEAN=0

WVAR=0

for i in $(seq "$MAX") 
do
    eval var$i=`./wrtest "$PRT2"`
done

for i in $(seq "$MAX")
do
    temp="var$i"
    # echo ${!temp}
    let WRSUM=WRSUM+temp
    let DWR=DWR+\(temp\*temp\)
done

let WRMEAN=WRSUM/MAX
let DWRMEAN=DWR/MAX
let WVAR=DWRMEAN-\(WRMEAN\*WRMEAN\)

echo long-input write mean=$WRMEAN
echo lont-input write var=$WVAR


for i in $(seq "$MAX") 
do
    #echo "$i"
    eval "open$i=`./openread openread.txt open`"
done

for i in $(seq "$MAX") 
do
    # echo "$i"
    eval "openwithwrite$i=`./openread openread.txt open write`"
done

for i in $(seq "$MAX") 
do
    # echo "$i"
    eval "read$i=`./openread openread.txt read`"
done
for i in $(seq "$MAX") 
do
    # echo "$i"
    eval "readwithwrite$i=`./openread openread.txt read write`"
done

for i in $(seq "$MAX") 
do
    # echo "$i"
    eval "readnum$i=`./test_read 30000`"
done

for i in $(seq "$MAX") 
do
    # echo "$i"
    eval "mkdir$i=`./test_mkdir`"
done

opensum=0
openwithwritesum=0
readsum=0
readwithwritesum=0
dopen=0
dopenw=0
dread=0
dreadw=0
bigread=0
mkdirsum=0
dmkdir=0
for i in $(seq "$MAX")
do
    temp="open$i"
    let opensum=opensum+temp
    let dopen=dopen+\(temp\*temp\)
done

for i in $(seq "$MAX")
do
    temp="openwithwrite$i"
    let openwithwritesum=openwithwritesum+temp
    let dopenw=dopenw+\(temp\*temp\)
done
for i in $(seq "$MAX")
do
    temp="read$i"
    let readsum=readsum+temp
    let dread=dread+\(temp\*temp\)
done
for i in $(seq "$MAX")
do
    temp="readwithwrite$i"
    let readwithwritesum=readwithwritesum+temp
    let dreadw=dreadw+\(temp\*temp\)
done

for i in $(seq "$MAX")
do
    temp="readnum$i"
    let bigread=bigread+temp
    let dbigread=dbigread+\(temp\*temp\)
done

for i in $(seq "$MAX")
do
    temp="mkdir$i"
    let mkdirsum=mkdirsum+temp
    let dmkdir=dmkdir+\(temp\*temp\)
done

let openmean=opensum/MAX
let dopenmean=dopen/MAX
let openvar=dopenmean-\(openmean\*openmean\)

let open_writemean=openwithwritesum/MAX
let dopen_writemean=dopenw/MAX
let wopenvar=dopen_writemean-\(open_writemean\*open_writemean\)

let read_mean=readsum/MAX
let dread_mean=dread/MAX
let readvar=dread_mean-\(read_mean\*read_mean\)

let read_writemean=readwithwritesum/MAX
let dreadw_mean=dreadw/MAX
let wreadvar=dreadw_mean-\(read_writemean\*read_writemean\)

let bigreadmean=bigread/MAX
let dbigread_mean=dbigread/MAX
let bigreadvar=dbigread_mean-\(bigreadmean\*bigreadmean\)

let mkdir_mean=mkdirsum/MAX
let dmkdir_mean=dmkdir/MAX
let mkdir_var=dmkdir_mean-\(mkdir_mean\*mkdir_mean\)

echo open mean=${openmean}
echo open var=${openvar}

echo open with write mean=${open_writemean}
echo open with write var=${wopenvar}

echo read mean=${read_mean}
echo read var=${readvar}

echo read with write mean=${read_writemean}
echo read with write var=${wreadvar}

echo bigread mean=${bigreadmean}
echo bigread var=${bigreadvar}

echo mkdir mean=${mkdir_mean}
echo mkdir var=${mkdir_var}
